version: '3.9'

services:


#db courier

  db:
    container_name: courier-db
    image: postgres:15.2
    volumes:
      - dbvolume:/var/lib/postgresql/dbvolume
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: courier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    deploy:
      restart_policy:
        condition: on-failure

#db user
  users-db:
    container_name: users-db
    image: postgres:15.2
    volumes:
      - usersvolume:/var/lib/postgresql/usersvolume
    ports:
      - "5431:5431"
    environment:
      PGPORT: 5431
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: unless-stopped

  #keycloak
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_PORT: 5431
      DB_ADDR: users-db
      DB_DATABASE: users
      DB_USER: postgres
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json"
    ports:
      - "8484:8080"
    volumes:
      - ./import/realm-export.json:/opt/jboss/keycloak/realm-export.json
    depends_on:
      - users-db
    links:
      - "users-db:users-db"




volumes:
  dbvolume:
  usersvolume:

