version: '3.9'

services:
  db:
    image: postgres:15.2
    restart: always
    ports:
      - '5444:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: courier