version: '3.9'

services:
  gateway-service:
    container_name: gateway
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      ISSUER_URI: http://keycloak:8080/auth/realms/my-app
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka
    ports:
      - '8080:8080'
    restart: always

  users-db:
    container_name: users-db
    image: postgres:15.2
    volumes:
      - usersvolume:/var/lib/postgresql/usersvolume
    ports:
      - "5431:5431"
    environment:
      PGPORT: 5431
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_PORT: 5431
      DB_ADDR: users-db
      DB_DATABASE: users
      DB_USER: postgres
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_HOSTNAME: keycloak
    ports:
       - "8484:8080"
    depends_on:
      - users-db
    links:
      - "users-db:users-db"




volumes:
  usersvolume: