server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetchRegistry: false
  instance:
    hostname: localhost
management:
  security:
    enabled: false